import Head from "next/head";
import Link from "next/link";
import { PropsWithChildren } from "react";
import { ConnectButton } from "@rainbow-me/rainbowkit";

export const Layout = (props: PropsWithChildren) => {
  return (
    <>
      <Head>
        <title>gratitude.party</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex min-h-screen flex-col justify-center bg-indigo-900 font-mono sm:pb-12">
        <div className="flex justify-end p-2">
          <ConnectButton showBalance={false} />
        </div>
        <main className="container relative mx-auto flex flex-1 flex-col overflow-hidden bg-white p-4 sm:max-w-sm sm:rounded">
          <div className="flex-1">{props.children}</div>
          <footer className="text-center text-xs">
            <div>
              crafted with{" "}
              <span className="relative animate-pulse text-pink-800">
                ♥<span className="absolute left-0 animate-ping">♥</span>
              </span>{" "}
              at{" "}
              <Link
                className="text-indigo-700 hover:text-indigo-500"
                target="_blank"
                href="https://supermodular.xyz"
              >
                supermodular.xyz
              </Link>
            </div>
            <div>we are building a more regenerative internet</div>
          </footer>
        </main>
      </div>
    </>
  );
};
